// Generates src/lib/companyRoutes.generated.ts: every company / project page, so the super
// admin console can show the same page under /admin/data/… (Company data).
// Usage: npm run routes:company   (run after adding or moving a page under (company) or (project))
import { readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const APP = "src/app";
const GROUPS = ["(company)", "(project)"];
const OUT = "src/lib/companyRoutes.generated.ts";

function pages(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) out.push(...pages(full));
    else if (name === "page.tsx") out.push(full);
  }
  return out;
}

const routes = GROUPS.flatMap((g) => pages(path.join(APP, g)))
  .map((file) => {
    const rel = path.relative(APP, file).split(path.sep);
    const segments = rel.slice(1, -1).map((s) => {
      const catchAll = /^\[\.\.\.(\w+)\]$/.exec(s);
      if (catchAll) return { kind: "catchAll", name: catchAll[1] };
      const param = /^\[(\w+)\]$/.exec(s);
      if (param) return { kind: "param", name: param[1] };
      return { kind: "static", name: s };
    });
    const importPath = "@/app/" + rel.join("/").replace(/\.tsx$/, "");
    return { segments, importPath };
  })
  .sort((a, b) => a.importPath.localeCompare(b.importPath));

const lines = routes.map(
  (r) =>
    `  { segments: ${JSON.stringify(r.segments)}, load: () => import(${JSON.stringify(r.importPath)}) },`,
);

writeFileSync(
  OUT,
  `// GENERATED by scripts/company-routes.mjs — do not edit. Run \`npm run routes:company\`.
import type { CompanyRoute } from "@/lib/companyRoutes";

export const COMPANY_ROUTES: CompanyRoute[] = [
${lines.join("\n")}
];
`,
);
console.log(`${routes.length} company / project pages → ${OUT}`);
